version: '3.8'

services:
  ollama:
    image: ollama/ollama:0.4.7
    volumes:
      - ./ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "11434:11434"
    restart: always
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
