version: '3.8'

services:
  doc_knowledgebase:
    build: .
    volumes:
      - ./html:/app/html
      - ./index.js:/app/index.js
    ports:
      # - "21080:8181"
      - "21080:21080"
    restart: always
    entrypoint: ["node", "/app/index.js"]
